
cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    yunhae:
      failed_login_attempts: 0
      logged_in: true
      name: yunhae
      password: $2b$12$zNNHxeYdScrQU2x7T4397eTdcpOdkEfC0C8oVwtqLbX.f4.nzwx6G
preauthorized:
  emails:
  - susu12356@gmail.com
